# -- Site Configuration --

theme = "congo"
themePath = "themes/congo"

defaultContentLanguage = "zh-Hans"
defaultAppearance = "light"
autoSwitchAppearance = true

[languages]
  [languages.zh-Hans]
    languageCode = "zh-Hans"
    languageName = "简体中文"
    weight = 1
    contentDir = "content"
  [languages.zh-Hant]
    languageCode = "zh-Hant"
    languageName = "繁體中文"
    weight = 2
    contentDir = "content"
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 3
    contentDir = "content"

enableRobotsTXT = true
summaryLength = 0

[pagination]
  pagerSize = 15

[outputs]
  home = ["HTML", "RSS", "JSON"]

[privacy]
  [privacy.vimeo]
    enableDNT = true
  [privacy.x]
    enableDNT = true
  [privacy.youTube]
    privacyEnhanced = true
